name: CI
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  checks:
    name: Lint/Typecheck/Build/Test
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Setup Node.js'
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 'lts/*'

      - name: 'Install Dependencies'
        run: npm clean-install

      - name: 'Lint'
        run: npm run lint

      - name: 'Typecheck'
        run: npm run typecheck

      - name: 'Build'
        run: npm run build

        # lints npm package for packaging errors to ensure compatibility across environments (https://github.com/bluwy/publint).
      # - name: 'Lint Packaging Errors'
      #  run: npx publint --strict

      - name: 'Test'
        run: npm run test
